name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.latest_vitepress_deploy }}
        TARGET_REPO: simply-none/latest-blogs
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: npm run build
        BUILD_DIR: docs/.vuepress/dist